import { Footer, Header } from "components";
import Head from "next/head";

type LayoutProps = {
  children: Array<React.ReactElement> | React.ReactElement;
};

export const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Kancelaria Restrukturyzacje</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
};
