import Head from "next/head";
import { Container, Hero, ServicesSection } from "components";
import useHeaderState from "hooks/useHeaderState";
import dynamic from "next/dynamic";

const AgentSwiper = dynamic(() =>
  import("components").then((module) => module.AgentSwiper)
);
export default function Home() {
  const { isMobile } = useHeaderState();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Container>
        {!isMobile && <AgentSwiper className="hidden sm:block" />}
        <ServicesSection />
      </Container>
    </>
  );
}
