name: Check

on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm prettier -c
